サインアップ機能開発
panda19931998/blog-system-5884 pull request #1
Opened 2019-03-25 05:17 UTC by panda19931998

サインアップ機能実装しました。

2019-03-29 14:50 UTC, halzion requested changes
ソースレビューを行いました。

2019-03-29 14:50 UTC, halzion commented on app/models/client/signup.php
> +session_regenerate_id(true);
session_regenerate_idは、ここではなく新規ユーザー登録処理後
自動ログインを行った際に行いましょう（105行目）

2019-03-29 14:50 UTC, halzion commented on app/models/client/signup.php
> +
利用規約／プライバシーポリシーの同意チェック処理が行われていないので追加しましょう。

2019-03-29 14:50 UTC, halzion commented on app/models/client/signup.php
> +	$client_code = $_POST['client_code'];
招待コードは「client_code」とは異なるため、「secret_code」という名前に変更してください。

2019-03-29 14:50 UTC, halzion commented on app/models/client/signup.php
> +            (client_name, password, mail_address, client_code, created_at, updated_at)
client_codeには、招待コードを登録するのではなく、
「ランダムな英数字12文字」を自動的に発行して登録するようにしましょう。

ランダムな文字列の生成は、str_shuffle、substrあたりを組み合わせれば出来るかと思います。

2019-03-29 14:50 UTC, halzion commented on app/models/client/signup.php
> +	}
招待コードは「BLOG_SYSTEM」と入力された場合のみ通過できるようにチェックを実装してください。

2019-04-02 21:41 UTC, keitokuta commented on app/models/client/signup.php
> +session_regenerate_id(true);
修正を確認しました。

2019-04-02 21:42 UTC, keitokuta commented on app/models/client/signup.php
> +
同意チェックされていなかった場合は、他の入力項目と同様にエラーメッセージを表示させるようにしましょう。

2019-04-02 21:42 UTC, keitokuta commented on app/models/client/signup.php
> +	$client_code = $_POST['client_code'];
修正を確認しました。

2019-04-02 21:42 UTC, keitokuta commented on app/models/client/signup.php
> +            (client_name, password, mail_address, client_code, created_at, updated_at)
修正を確認しました。

2019-04-02 21:42 UTC, keitokuta commented on app/models/client/signup.php
> +	}
修正を確認しました。

2019-04-02 21:44 UTC, keitokuta reviewed
修正が必要な部分を追記しました。

2019-04-02 21:44 UTC, keitokuta commented on app/models/client/signup.php
> +								<input type="text" name="client_name" class="form-control" placeholder="" required />
全ての入力項目についてですが、エラーが発生した場合に入力値が保持されません。

2019-04-04 10:40 UTC, keitokuta commented on app/models/client/signup.php
> +
修正を確認しました。

2019-04-04 10:41 UTC, keitokuta commented on app/models/client/signup.php
> +								<input type="text" name="client_name" class="form-control" placeholder="" required />
修正を確認しました。

2019-04-04 10:41 UTC, merged