ログイン機能開発
panda19931998/blog-system-5884 pull request #2
Opened 2019-04-18 12:28 UTC by panda19931998

ログイン機能実装終わりました。

2019-04-20 04:05 UTC, panda19931998 commented
login,signup,commonのインデント修正しました。

2019-04-22 08:22 UTC, keitokuta requested changes
レビューコメントを記載しました。

2019-04-22 08:22 UTC, keitokuta commented on app/models/client/login.php
> +			setcookie('BLOG_SYSTEM', '', time()-86400, '/dev/blog-system-5884/web/');
Cookieの有効パスは、本番環境でもそのまま使えるように「/」にしておきましょう。

2019-04-22 08:22 UTC, keitokuta commented on app/models/client/login.php
> +			setcookie('BLOG_SYSTEM', $auto_login_key, time()+3600*24*365, '/dev/blog-system-5884/web/');
Cookieの有効パスは、本番環境でもそのまま使えるように「/」にしておきましょう。

2019-04-22 08:22 UTC, keitokuta commented on app/models/client/login.php
> +		header('Location:'.SITE_URL.'/blog');
ログイン後、正常に画面が表示されないため、パスの末尾に/を付けて「/blog/」としましょう。

2019-04-22 08:22 UTC, keitokuta commented on app/models/client/login.php
> +<link rel="apple-touch-icon" sizes="180x180" href="<?php echo CONTENTS_SERVER_URL ?>/img/apple-touch-icon-180x180.png">
favicon画像が配置されていないようですので、
以下より画像をダウンロードして設置してください。
https://demo.flu-x.net/contents/img/favicon.ico
https://demo.flu-x.net/contents/img/apple-touch-icon-180x180.png

2019-04-23 04:22 UTC, panda19931998 commented
login.phpのクッキー有効パス、favicon画像など修正しました。

2019-04-23 08:51 UTC, merged