カテゴリー管理機能
panda19931998/blog-system-5884 pull request #4
Opened 2019-06-03 12:29 UTC by panda19931998

新規登録、変更機能を実装しましたのでチェックよろしくお願いします。

2019-06-04 03:12 UTC, keitokuta requested changes

2019-06-04 03:12 UTC, keitokuta commented on app/models/blog/category.php
> +$sql = "select * from blog_category_master where client_id = :client_id ";
カテゴリーの検索は「client_id」ではなく「blog_id」で行いましょう。
クライアント > ブログ > カテゴリーという階層構造になります。

2019-06-04 03:12 UTC, keitokuta commented on app/models/blog/category.php
> +foreach ($stmt->fetchAll() as $row) {
このforeachループは不要です。

$blog_category_masters = $stmt->fetchAll();

と書くだけで、配列が取得できます。

2019-06-04 03:12 UTC, keitokuta commented on app/models/blog/category.php
> +<?php
PHPブロックはここではなく、ファイルの上部に書いて
HTMLブロックと分けるようにしましょう。

ファイルの前半：PHPブロック
ファイルの後半：HTMLブロック

となっていた方が見やすいです。

2019-06-04 03:12 UTC, keitokuta commented on app/models/blog/category_entry.php
> +// ログインチェック
全ファイル共通ですが、

・ログインチェック
・セッションからユーザーを取得
・connectDb()

といった共通処理は、各PHPファイルではなく
app/index.phpにて一括して行うようにしましょう。

2019-06-04 03:12 UTC, keitokuta commented on app/models/blog/category_entry.php
> +	// データベース（blogテーブル）からblog_idを取得する。
blog_idの取得処理も、app/index.phpにて行いましょう。

2019-06-04 03:12 UTC, keitokuta commented on app/models/blog/category_entry.php
> +	$sql = "select * from blog_category_master where blog_category_slug = :blog_category_slug  limit 1";
スラッグの重複確認は、blog_idごとになります。
（WHERE条件にblog_idを入れましょう）

2019-06-04 03:12 UTC, keitokuta commented on app/models/blog/category_entry_edit.php
> +<?php
新規登録、変更処理はどちらもcategory_entry.phpで行うようにしましょう。

パラメーターでblog_category_codeが渡された場合は「変更モード」
渡されなかった場合は「新規モード」になります。

2019-06-04 03:12 UTC, keitokuta commented on app/url_list.php
> +$url_list["/blog/category_entry_edit/"] = "/models/blog/category_entry_edit.php";
category_entry.phpにまとめましょう。

2019-06-09 00:53 UTC, keitokuta commented on app/models/blog/category_entry.php
> +// ログインチェック
unset($pdo)も同様ですね。

2019-06-12 08:03 UTC, keitokuta commented on app/models/blog/category_entry.php
> +// ログインチェック
login.php、logout.phpも同様に修正しましょう。

また、index.phpの↓の中でもunset($pdo)を行うようにしましょう。
エラーが発生した場合は、ここに直接飛んできますので。
} catch (Exception $e) {
}

2019-06-12 08:03 UTC, keitokuta commented on app/models/blog/category_entry.php
> +	$sql = "select * from blog_category_master where blog_category_slug = :blog_category_slug  limit 1";
これがまだ直っていないようです。

2019-06-13 12:09 UTC, panda19931998 commented
caegory_entry.phpのblog_idの取得部分とindex.phpのunset($pdo)の修正終わりました。

よろしくお願いします。

2019-06-15 04:23 UTC, keitokuta requested changes

2019-06-15 04:23 UTC, keitokuta commented on app/models/blog/category_entry.php
> +<?php
・登録画面で入力エラーが発生した際、入力値が保持されず消えてしまいます。

2019-06-15 04:23 UTC, keitokuta commented on app/models/blog/category_entry.php
> +
・スラッグが未入力だった場合は、DBには空のまま登録してください。（1.htmlのようにアクセス出来るようにするのは公開側の処理で行います）

2019-06-15 13:32 UTC, panda19931998 commented
入力値が保持についてとスラッグが未入力の時のＤＢ登録のところを修正しました。

よろしくお願いします。

2019-06-19 14:56 UTC, panda19931998 commented
カテゴリー削除機能の実装が終わりました。
よろしくお願いします。

2019-06-23 12:41 UTC, panda19931998 commented
以下の３点の修正をしました。

・カテゴリー削除時のblog_category_code_sequenceをマイナスしてしまっているところ
・blog_categoryテーブルに入っている該当カテゴリーのデータの削除を追加
・カテゴリー一覧画面にて「カテゴリーが登録されていません」のメッセージの配置を変更

よろしくお願いします。

2019-06-26 08:32 UTC, panda19931998 commented
blog_category_master_idによる削除とblog_category_masterテーブルからのデータの取得の部分を修正しました。

よろしくお願いします。

2019-06-27 02:49 UTC, keitokuta requested changes

2019-06-27 02:49 UTC, keitokuta commented on app/models/blog/delete.php
> +$sql = "select * from blog_category_master where blog_category_code = :blog_category_code and client_id = :client_id and blog_id =:blog_id limit 1";
$idが設定されていた場合のみ、以下のDB処理を行うようにしましょう。

2019-06-27 02:49 UTC, keitokuta commented on app/models/blog/delete.php
> +//blog_category_masterのカテゴリーを削除
$blog_category_masterが取得出来た場合のみ、以下のDB処理を行うようにしましょう。

2019-06-29 13:31 UTC, panda19931998 commented
値のチェックの修正をしました。

よろしくお願いします。

2019-07-01 12:32 UTC, panda19931998 commented
$idのチェックを修正しました。

2019-07-02 13:35 UTC, panda19931998 commented
修正前の状態にもどしました。

よろしくお願いします。

2019-07-24 14:59 UTC, panda19931998 commented
ブログカテゴリーの一覧を取得・表示し、
フリーワードで検索出来るように検索機能を実装しました。

2019-08-15 08:12 UTC, panda19931998 commented
キーワード検索した際のSELECT文とカテゴリー一覧画面の「記事数」を修正しました。

よろしくお願いします。

2019-08-18 07:53 UTC, panda19931998 commented
新規ユーザー登録（signup.php）のstatus、templates/header.php「ログアウト」のリンク修正しました。
それからsignup.phpにfaviconの指定行ですが、自分のコードを確認するとheadタグ内の一番最後のところに記入しているのですが。
以前からよくsignup.phpは何かコードが勝手に書き換わってることがあったのでなにかatomを閉じて起動するたびに不具合が起きているような気がします。

以上です。よろしくお願いします。

2019-08-22 06:56 UTC, panda19931998 commented
新規ユーザー登録、ブログカテゴリー一覧の表示動作確認しました。

よろしくお願いします。

2019-08-24 13:09 UTC, panda19931998 commented
ブログカテゴリー一覧画面の記事数の列の右の「2」の表示を削除しました。

よろしくお願いします。

2019-08-27 07:10 UTC, panda19931998 commented
ブログカテゴリー登録画面の緑の枠の表示と記事数の中央寄せ修正しました。

よろしくお願いします。

2019-08-28 16:25 UTC, merged